---
title: "Quote by Björn Ulvaeus"
date: "2025"
categories: [quotes]
---

::: {.quote-container}
::: {.quote-text}
“[AI] is in no way a substitute for a songwriting partner,” he says. “No, it’s a tool. But it’s a great tool that never existed before, where you can reference anything in the world of music, and which you can use as a sounding board, and you can try new things on.” He continues: “For instance, when I’ve written something, maybe eight bars, I can record them with a lyric, and just ask it, where would you take me if you went into this or that realm of music? What would it sound like? Usually it comes back with garbage, but sometimes there is something that might point me in a new direction. “I can get in touch with my AI at any time. If I wake up in the middle of the night, I can try new things. Whenever you feel like it, whenever you have an idea, you can try it out with your AI partner."
:::
::: {.quote-author}
— [ABBA‘s Björn Ulvaeus](https://musictech.com/news/music/bjorn-ulvaeus-says-ai-is-unstoppable/#:~:text=“%5BAI%5D%20is%20in%20no,can%20try%20new%20things%20on.”)
:::
:::
