project:
  type: website

website:
  title: "Everton Eduardo Colombo"
  description: "Personal Blog"
  site-url: "https://evertoncolombo.github.io/blog/"
  llms-txt: true
  navbar:
    background: primary
    left:
      - text: "Feed"
        href: index.qmd
      - text: "Quotes"
        href: quotes/index.qmd
      - text: "Datasets"
        href: datasets.qmd
      - text: "Watch"
        href: watch/index.qmd
      - text: "TIL"
        href: til.qmd
      - text: "Consulting"
        href: consulting.qmd
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/EvertonColombo

format:
  html:
    theme:
      light: morph
      dark: cyborg
    toc: true
    css: styles.css