---
title: "Quotes"
---

## 2026

## 2025

::: {.quote-container}
::: {.quote-text}
"We should create a human-in-the-loop AI that would help our pathologists be better at reaching the diagnosis, not tell them what the diagnosis is."
:::
::: {.quote-author}
— [Thomas Montine, MD, PhD, Chair, Department of Pathology at Stanford University](https://stanmed.stanford.edu/digitizing-pathology-samples-better-analysis/09/ai-tool-pathologists.html)
:::
:::

::: {.quote-container}
::: {.quote-text}
"You are more certain of the fact of knowing than of anything that you know. The known can always be doubted. This might not be a material world; it might not be the way it appears to be.
But even if it is an illusion, the knowing by which that illusion is known must be real, because an unreal knowing or an unreal consciousness could not know anything."
:::
::: {.quote-author}
— [Rupert Spira](https://rupertspira.com/)
:::
:::

::: {.quote-container}
::: {.quote-text}
"Claude doesn't make me much faster on the work that I am an expert on. Maybe 15-20% depending on the day. It's the work that I don't know how to do and would have to research. Or the grunge work I don't even want to do. On this it is hard to even put a number on. Many of the projects I do with Claude day to day I just wouldn't have done at all pre-Claude."
:::
::: {.quote-author}
— [Aaron Boodman](https://x.com/aboodman/status/1982898753607741502)
:::
:::

::: {.quote-container}
::: {.quote-text}
"A real gap between what people using chatbots can do and what even non-coders can do with today’s CLI-like tools that have access to their computers, the web & the ability to execute long-term plans. Big opportunity for the AI lab that gets powerful & safe personal agents right."
:::
::: {.quote-author}
— [Ethan Mollick](https://www.oneusefulthing.org/)
:::
:::

::: {.quote-container}
::: {.quote-text}
"Three years ago, we were impressed that a machine could write a poem about otters. Less than 1,000 days later, I am debating statistical methodology with an agent that built its own research environment. The era of the chatbot is turning into the era of the digital coworker. To be very clear, Gemini 3 isn’t perfect, and it still needs a manager who can guide and check it. But it suggests that “human in the loop” is evolving from “human who fixes AI mistakes” to “human who directs AI work.” And that may be the biggest change since the release of ChatGPT."
:::
::: {.quote-author}
— [Ethan Mollick](https://www.oneusefulthing.org/)
:::
:::

::: {.quote-container}
::: {.quote-text}
"I’m starting to get into a habit of reading everything (blogs, articles, book chapters,…) with LLMs. Usually pass 1 is manual, then pass 2 “explain/summarize”, pass 3 Q&A. I usually end up with a better/deeper understanding than if I moved on. Growing to among top use cases.

On the flip side, if you’re a writer trying to explain/communicate something, we may increasingly see less of a mindset of “I’m writing this for another human” and more “I’m writing this for an LLM”. Because once an LLM “gets it”, it can then target, personalize and serve the idea to its user."
:::
::: {.quote-author}
— [Andrej Karpathy](https://twitter.com/karpathy)
:::
:::

::: {.quote-container}
::: {.quote-text}
"I doubt that anything resembling genuine "artificial general intelligence" is within reach of current #AI tools.  However, I think a weaker, but still quite valuable, type of "artificial general cleverness" is becoming a reality in various ways."
:::
::: {.quote-author}
— [Terence Tao](https://mathstodon.xyz/@tao)
:::
:::

::: {.quote-container}
::: {.quote-text}
“[AI] is in no way a substitute for a songwriting partner. No, it’s a tool. But it’s a great tool that never existed before, where you can reference anything in the world of music, and which you can use as a sounding board, and you can try new things on.” He continues: “For instance, when I’ve written something, maybe eight bars, I can record them with a lyric, and just ask it, where would you take me if you went into this or that realm of music? What would it sound like? Usually it comes back with garbage, but sometimes there is something that might point me in a new direction. “I can get in touch with my AI at any time. If I wake up in the middle of the night, I can try new things. Whenever you feel like it, whenever you have an idea, you can try it out with your AI partner."
:::
::: {.quote-author}
— [ABBA‘s Björn Ulvaeus](https://musictech.com/news/music/bjorn-ulvaeus-says-ai-is-unstoppable/#:~:text=“%5BAI%5D%20is%20in%20no,can%20try%20new%20things%20on.”)
:::
:::
